# Generated by Django 2.1.5 on 2019-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.TextField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
