# Generated by Django 2.1.5 on 2019-01-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190124_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
