# Generated by Django 2.1.5 on 2019-01-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190124_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='par',
        ),
    ]
